### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by kamoltat** [ceph/pulpito-ng#3]
**Current progress:**

In `teuthology-api` you can authenticate with github (you have to be a member of ceph organization) which gives you permission to use `teuthology-suite` and `teuthology-kill`.

**Todo**

- [x] 1. pulpito-ng should have a login/logout button displaying username (or icon) on top right corner.
- [x] 2. Basically login button calls the `login` `logout` endpoint in teuthology-api.
- [ ] 3. Incorporate some sort of unit-test to this.

**Comment by VallariAg** [comment]
Linking issue for adding unit-tests: https://github.com/ceph/teuthology-api/issues/5
